//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laba5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string SurName { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public int Type { get; set; }
        public bool IsMaster { get; set; }
        public bool IsCandidat { get; set; }
        public bool IsDoctor { get; set; }
        public string Curse { get; set; }
        public string Faculty { get; set; }
        public string StructPidr { get; set; }
        public byte[] Picture { get; set; }
        public bool IsVerificated { get; set; }
        public string SystemCode { get; set; }
        public string PictureType { get; set; }
    }
}
